RTE of ocrmypdf
ocrmypdf expects locales:

```
RuntimeError: ocrmypdf will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.
This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
```